# Generated by Django 4.2.4 on 2023-09-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='nima', max_length=100),
            preserve_default=False,
        ),
    ]
